import { ImageItem } from './types';
import { getPlaceholderImage, getPlaceholderThumbnail } from './utils';

// Historical images from Myanmar's past with multi-language support
export const sampleImages: ImageItem[] = [
  {
    id: '1',
    title: {
      my: 'ရန်ကုန်တက္ကသိုလ် ကျောင်းသားမှတ်ပုံတင် - ၁၉၅၉-၁၉၆၀',
      en: 'University of Rangoon Student ID - 1959-1960',
      zh: '仰光大学学生证 - 1959-1960',
      de: 'Universität Rangoon Studentenausweis - 1959-1960',
    },
    description: {
      my: 'ရန်ကုန်တက္ကသိုလ် (ယခု ရန်ကုန်တက္ကသိုလ်) မှ ၁၉၅၉-၁၉၆၀ ပညာသင်နှစ်အတွက် ခေတ်ဟောင်း ကျောင်းသားမှတ်ပုံတင်။ ဤကတ်ပြားသည် Babu Dawood Ganda ဆိုသော B.A. ကျောင်းသားတစ်ဦး၏ ပိုင်ဆိုင်မှုဖြစ်ပြီး ပတ်စပို့အရွယ် ဓာတ်ပုံ၊ လက်ရေးဖြင့် ရေးသားထားသော ကိုယ်ရေးအချက်အလက်များနှင့် တက္ကသိုလ်၏ တရားဝင် တံဆိပ်များ ပါဝင်သည်။',
      en: 'A vintage student identification card from the University of Rangoon (now University of Yangon) for the academic year 1959-1960. The card belongs to Babu Dawood Ganda, a B.A. student, and features a passport-sized photograph, handwritten personal details, and official university stamps.',
      zh: '仰光大学（现仰光大学）1959-1960学年的复古学生身份证。该卡属于B.A.学生Babu Dawood Ganda，包含护照尺寸照片、手写个人信息和官方大学印章。',
      de: 'Ein altmodischer Studentenausweis der Universität Rangoon (heute Universität Yangon) für das akademische Jahr 1959-1960. Die Karte gehört Babu Dawood Ganda, einem B.A.-Studenten, und enthält ein passbildgroßes Foto, handgeschriebene persönliche Daten und offizielle Universitätsstempel.',
    },
    year: 1959,
    decade: '1950s',
    era: 'Post-Independence',
    location: {
      my: 'ရန်ကုန်',
      en: 'Rangoon (Yangon)',
      zh: '仰光',
      de: 'Rangoon (Yangon)',
    },
    category: {
      my: 'ပညာရေး',
      en: 'Education',
      zh: '教育',
      de: 'Bildung',
    },
    tags: {
      my: ['ပညာရေး', 'တက္ကသိုလ်', 'ကျောင်းသား', 'မှတ်တမ်း', 'မှတ်ပုံတင်', '၁၉၅၀'],
      en: ['education', 'university', 'student', 'document', 'identification', '1950s'],
      zh: ['教育', '大学', '学生', '文件', '身份证明', '1950年代'],
      de: ['Bildung', 'Universität', 'Student', 'Dokument', 'Ausweis', '1950er'],
    },
    imageUrl: '/images/university-rangoon-student-id-1959.jpg',
    thumbnailUrl: '/images/university-rangoon-student-id-1959.jpg',
    historicalContext: {
      my: 'ရန်ကုန်တက္ကသိုလ်သည် ဤကာလအတွင်း မြန်မာနိုင်ငံ၏ အဓိက ပညာရေးအဖွဲ့အစည်းဖြစ်ခဲ့သည်။ ဤကျောင်းသားမှတ်ပုံတင်ကတ်ပြားသည် လွတ်လပ်ရေးရပြီးနောက် ခေတ်တွင် အဆင့်မြင့်ပညာရေး ဖွံ့ဖြိုးတိုးတက်လာပုံကို ကိုယ်စားပြုသည်။ ဤမှတ်တမ်းသည် တရားဝင် စာရင်းသွင်းမှု လုပ်ငန်းစဉ်နှင့် တက္ကသိုလ်၏ အုပ်ချုပ်ရေး ဖွဲ့စည်းပုံကို ပြသနေသည်။ ကျောင်းသားနှင့် Registrar နှစ်ဦးစလုံး၏ လက်မှတ်များ ပါဝင်သည်။ "134, 37th Street, Rangoon" လိပ်စာသည် ထိုခေတ်က မြို့ပြ မြင်ကွင်းကို ထင်ဟပ်စေသည်။',
      en: 'The University of Rangoon was the premier educational institution in Myanmar during this period. This student ID card represents the post-independence era when higher education was expanding. The document shows the formal registration process and the university\'s administrative structure, with signatures from both the student and the Registrar. The address "134, 37th Street, Rangoon" reflects the urban landscape of the time.',
      zh: '仰光大学是这一时期缅甸的主要教育机构。这张学生证代表了独立后高等教育扩张的时代。该文件显示了正式的注册过程和大学的行政结构，包括学生和注册主任的签名。"134, 37th Street, Rangoon"地址反映了当时的城市景观。',
      de: 'Die Universität Rangoon war in dieser Zeit die führende Bildungseinrichtung in Myanmar. Dieser Studentenausweis repräsentiert die Zeit nach der Unabhängigkeit, als die Hochschulbildung expandierte. Das Dokument zeigt den formalen Registrierungsprozess und die Verwaltungsstruktur der Universität mit Unterschriften von sowohl dem Studenten als auch dem Registrar. Die Adresse "134, 37th Street, Rangoon" spiegelt die städtische Landschaft der Zeit wider.',
    },
    source: {
      my: 'သမိုင်းဝင် စုစည်းရာ',
      en: 'Historical Archive Collection',
      zh: '历史档案收藏',
      de: 'Historisches Archiv',
    },
  },
  {
    id: '2',
    title: {
      my: 'KAPITAN ဆေးလိပ် ကြော်ငြာ - ခေတ်ဟောင်း',
      en: 'KAPITAN Cigarettes Advertisement - Vintage',
      zh: 'KAPITAN 香烟广告 - 复古',
      de: 'KAPITAN Zigarettenwerbung - Vintage',
    },
    description: {
      my: 'KAPITAN ဆေးလိပ်အမှတ်တံဆိပ်၏ ခေတ်ဟောင်း အနက်ရောင်-အဖြူရောင် ကြော်ငြာတစ်ခု၊ အမျိုးသားတစ်ဦးက အမျိုးသမီးတစ်ဦးအား ဆေးလိပ်ထွန်းပေးနေသော ပုံဆွဲထားသော မြင်ကွင်းနှင့် ဆေးလိပ်ဗူးအဝိုင်းကို ထင်ရှားစွာ ပြသထားသည်။ ကြော်ငြာတွင် မြန်မာစာနှင့် အင်္ဂလိပ်စာ ဘရန်ဒင်းများ ပါဝင်သည်။',
      en: 'A vintage monochrome advertisement for KAPITAN brand cigarettes, featuring an illustrated scene of a man lighting a cigarette for a woman, alongside a prominent display of the round cigarette tin. The advertisement includes Burmese script and English branding.',
      zh: 'KAPITAN品牌香烟的复古单色广告，描绘了一个男人为女人点烟的场景，以及醒目的圆形香烟罐展示。广告包含缅甸文字和英文品牌。',
      de: 'Eine altmodische monochrome Werbung für KAPITAN-Zigaretten mit einer illustrierten Szene, in der ein Mann einer Frau eine Zigarette anzündet, neben einer prominenten Darstellung der runden Zigarettendose. Die Werbung enthält burmesische Schrift und englische Markenbezeichnung.',
    },
    year: 1960,
    decade: '1960s',
    era: 'Post-Independence',
    location: {
      my: 'မြန်မာ',
      en: 'Myanmar',
      zh: '缅甸',
      de: 'Myanmar',
    },
    category: {
      my: 'ကုန်သွယ်ရေး',
      en: 'Commerce',
      zh: '商业',
      de: 'Handel',
    },
    tags: {
      my: ['ကြော်ငြာ', 'ဆေးလိပ်', 'ကုန်သွယ်ရေး', 'ခေတ်ဟောင်း-ကြော်ငြာ', 'စျေးကွက်', '၁၉၆၀'],
      en: ['advertisement', 'cigarettes', 'commerce', 'vintage-ad', 'marketing', '1960s'],
      zh: ['广告', '香烟', '商业', '复古广告', '营销', '1960年代'],
      de: ['Werbung', 'Zigaretten', 'Handel', 'Vintage-Werbung', 'Marketing', '1960er'],
    },
    imageUrl: '/images/kapitan-cigarettes-ad.jpg',
    thumbnailUrl: '/images/kapitan-cigarettes-ad.jpg',
    historicalContext: {
      my: 'ဤကြော်ငြာသည် ၁၉၆၀ ပြည့်လွန်နှစ်များက မြန်မာနိုင်ငံ၏ ကုန်သွယ်ရေး မြင်ကွင်းကို ထင်ဟပ်စေသည်၊ နိုင်ငံတကာ အမှတ်တံဆိပ်များကို ဒေသတွင်း စားသုံးသူများထံ မည်သို့ စျေးကွက်တင်ရောင်းချခဲ့ကြောင်း ပြသနေသည်။ ပုံဆွဲပုံစံသည် ၂၀ ရာစု အလယ်ပိုင်း ကြော်ငြာများ၏ လက္ခဏာရပ်ဖြစ်ပြီး၊ ထုတ်ကုန်များကို မြှင့်တင်ရန် လူမှုရေး မြင်ကွင်းများကို အသုံးပြုသည်။ မြန်မာစာနှင့် အင်္ဂလိပ်စာ နှစ်မျိုးလုံး ပါဝင်မှုသည် ဤကာလအတွင်း ကုန်သွယ်ရေး ဆက်သွယ်မှု၏ နှစ်ဘာသာ သဘာဝကို ညွှန်ပြနေသည်။',
      en: 'This advertisement reflects the commercial landscape of 1960s Myanmar, showing how international brands were marketed to local consumers. The illustration style is characteristic of mid-20th century advertising, using social scenes to promote products. The presence of both Burmese and English text indicates the bilingual nature of commercial communication during this period.',
      zh: '这则广告反映了1960年代缅甸的商业景观，展示了国际品牌如何向本地消费者营销。插图风格是20世纪中期广告的特征，使用社交场景来推广产品。缅甸文字和英文的存在表明这一时期商业交流的双语性质。',
      de: 'Diese Werbung spiegelt die Handelslandschaft Myanmars in den 1960er Jahren wider und zeigt, wie internationale Marken an lokale Verbraucher vermarktet wurden. Der Illustrationsstil ist charakteristisch für Werbung aus der Mitte des 20. Jahrhunderts und verwendet soziale Szenen zur Produktwerbung. Das Vorhandensein sowohl von burmesischem als auch von englischem Text zeigt die zweisprachige Natur der kommerziellen Kommunikation in dieser Zeit.',
    },
    source: {
      my: 'ခေတ်ဟောင်း ကြော်ငြာ စုစည်းရာ',
      en: 'Vintage Advertisement Collection',
      zh: '复古广告收藏',
      de: 'Vintage-Werbesammlung',
    },
  },
  {
    id: '3',
    title: {
      my: 'ဘုရားပုထိုးစဉ် မြင်ကွင်း - ပုထိုးတည်ဆောက်မှု',
      en: 'Temple Complex Scene - Pagoda Construction',
      zh: '寺庙群场景 - 佛塔建设',
      de: 'Tempelkomplex-Szene - Pagodenbau',
    },
    description: {
      my: 'ပုထိုးကြီးတစ်ခု တည်ဆောက်နေစဉ်၊ အနုစိတ် သစ်သား ရှုမျှော်ခင်းများ၊ ရှေးရိုးရာ ရုပ်တုများနှင့် ရှေးရိုးရာ ဝတ်စားဆင်ယင်ထားသော လူများ ပါဝင်သော ဘုရားပုထိုးစဉ် မြင်ကွင်းကို ဖမ်းယူထားသော ခေတ်ဟောင်း sepia-toned ဓာတ်ပုံတစ်ပုံ။ ပုံသည် ရှေးရိုးရာ ဗိသုကာလက်ရာများနှင့် လှုပ်ရှားမှုများသော ပြည်သူ့ စုဝေးရာ နေရာတစ်ခုကို ပြသနေသည်။',
      en: 'A sepia-toned vintage photograph capturing a bustling temple complex scene with a large stupa under construction, ornate wooden pavilions, traditional statues, and people in traditional attire. The image shows intricate traditional architecture and a vibrant public gathering space.',
      zh: '一张复古的棕褐色调照片，捕捉了一个繁忙的寺庙群场景，包括正在建设中的大型佛塔、华丽的木制亭子、传统雕像和穿着传统服装的人们。图像展示了复杂的传统建筑和充满活力的公共聚会空间。',
      de: 'Ein sepia-getöntes Vintage-Foto, das eine geschäftige Tempelkomplex-Szene mit einem großen, im Bau befindlichen Stupa, kunstvollen Holzpavillons, traditionellen Statuen und Menschen in traditioneller Kleidung einfängt. Das Bild zeigt aufwendige traditionelle Architektur und einen lebendigen öffentlichen Versammlungsort.',
    },
    year: 1965,
    decade: '1960s',
    era: 'Post-Independence',
    location: {
      my: 'မြန်မာ',
      en: 'Myanmar',
      zh: '缅甸',
      de: 'Myanmar',
    },
    category: {
      my: 'ဗိသုကာ',
      en: 'Architecture',
      zh: '建筑',
      de: 'Architektur',
    },
    tags: {
      my: ['ဘုရား', 'ပုထိုး', 'ဗိသုကာ', 'ဘာသာရေး', 'တည်ဆောက်မှု', 'ရှေးရိုးရာ', 'စေတီ'],
      en: ['temple', 'pagoda', 'architecture', 'religion', 'construction', 'traditional', 'stupa'],
      zh: ['寺庙', '佛塔', '建筑', '宗教', '建设', '传统', '佛塔'],
      de: ['Tempel', 'Pagode', 'Architektur', 'Religion', 'Bau', 'traditionell', 'Stupa'],
    },
    imageUrl: '/images/temple-complex-pagoda-construction.jpg',
    thumbnailUrl: '/images/temple-complex-pagoda-construction.jpg',
    historicalContext: {
      my: 'ဤဓာတ်ပုံသည် မြန်မာနိုင်ငံ၏ သန့်ရှင်းသော ဗုဒ္ဓဘာသာ နေရာများ၏ ဆက်လက် တည်ဆောက်မှုနှင့် ထိန်းသိမ်းမှုကို ဖမ်းယူထားသည်။ စေတီပတ်လည်တွင် မြင်ရသော scaffolding သည် ဤအဆောက်အဦများအတွက် လိုအပ်သော ဆက်လက် စောင့်ရှောက်မှုနှင့် ပြန်လည် ပြုပြင်မှုကို ပြသနေသည်။ အနုစိတ် သစ်သား ရှုမျှော်ခင်းသည် မြန်မာ့ ဗိသုကာ လက်ရာများကို ကိုယ်စားပြုပြီး၊ ရှေးရိုးရာ longyi ဝတ်ဆင်ထားသော လူများ၏ ရှိနေမှုသည် နေ့စဉ် ဘဝနှင့် ဘာသာရေး လုပ်ဆောင်မှုကို ထင်ဟပ်စေသည်။ ထိုကဲ့သို့သော ဘုရားပုထိုးစဉ်များသည် ဝိညာဉ်ရေးရာ စင်တာများနှင့် အသိုင်းအဝိုင်း စုဝေးရာ နေရာများ အဖြစ် ဆောင်ရွက်ခဲ့သည်။',
      en: 'This photograph captures the ongoing construction and maintenance of Myanmar\'s sacred Buddhist sites. The visible scaffolding around the stupa shows the continuous care and renovation these structures require. The ornate wooden pavilion represents traditional Myanmar architectural craftsmanship, while the presence of people in traditional longyi reflects daily life and religious practice. Such temple complexes served as both spiritual centers and community gathering places.',
      zh: '这张照片捕捉了缅甸神圣佛教场所的持续建设和维护。佛塔周围可见的脚手架显示了这些结构所需的持续护理和翻新。华丽的木制亭子代表了传统的缅甸建筑工艺，而穿着传统笼基的人们反映了日常生活和宗教实践。这样的寺庙群既是精神中心，也是社区聚会场所。',
      de: 'Dieses Foto erfasst die fortlaufende Konstruktion und Wartung der heiligen buddhistischen Stätten Myanmars. Das sichtbare Gerüst um den Stupa zeigt die kontinuierliche Pflege und Renovierung, die diese Strukturen erfordern. Der kunstvolle Holzpavillon repräsentiert traditionelles myanmarisches Architekturhandwerk, während die Anwesenheit von Menschen in traditionellen Longyi das tägliche Leben und die religiöse Praxis widerspiegelt. Solche Tempelkomplexe dienten sowohl als spirituelle Zentren als auch als Gemeinschaftsversammlungsorte.',
    },
    source: {
      my: 'ဓာတ်ပုံ စုစည်းရာ',
      en: 'Photographic Archive',
      zh: '摄影档案',
      de: 'Fotografisches Archiv',
    },
  },
  {
    id: '4',
    title: {
      my: 'စားသောက်ဆိုင် မီနူ - အအေးသောက်စရာ စျေးနှုန်းစာရင်း',
      en: 'Restaurant Menu - Cold Drinks Price List',
      zh: '餐厅菜单 - 冷饮价格表',
      de: 'Restaurant-Menü - Kaltgetränke-Preisliste',
    },
    description: {
      my: 'မြန်မာနိုင်ငံမှ ခေတ်ဟောင်း စားသောက်ဆိုင် မီနူ သို့မဟုတ် စျေးနှုန်းစာရင်း၊ ရေခဲမုန့်၊ အအေးသောက်စရာ အမျိုးမျိုး (Horlicks, Milo, Cocoa, Ovaltine, Nescafe)၊ သစ်သီးအခြေခံ သောက်စရာများနှင့် အချိုပွဲများ ပါဝင်သော ၂၁ ခု စာရင်း။ မှတ်တမ်းသည် မြန်မာစာဖြင့် ရေးသားထားပြီး ကျပ်နှင့် ပြားဖြင့် စျေးနှုန်းများ ပါဝင်သည်။',
      en: 'A vintage restaurant menu or price list from Myanmar, featuring a table of 21 items including ice cream, various cold drinks (Horlicks, Milo, Cocoa, Ovaltine, Nescafe), fruit-based beverages, and desserts. The document is in Burmese script with prices in Kyat and Pya.',
      zh: '来自缅甸的复古餐厅菜单或价格表，包含21个项目，包括冰淇淋、各种冷饮（Horlicks、Milo、Cocoa、Ovaltine、Nescafe）、水果饮料和甜点。文件使用缅甸文字，价格以缅元和分计价。',
      de: 'Ein altmodisches Restaurant-Menü oder Preisliste aus Myanmar mit einer Tabelle von 21 Artikeln, einschließlich Eiscreme, verschiedenen Kaltgetränken (Horlicks, Milo, Cocoa, Ovaltine, Nescafe), fruchtbasierten Getränken und Desserts. Das Dokument ist in burmesischer Schrift mit Preisen in Kyat und Pya.',
    },
    year: 1970,
    decade: '1970s',
    era: 'Socialist Era',
    location: {
      my: 'မြန်မာ',
      en: 'Myanmar',
      zh: '缅甸',
      de: 'Myanmar',
    },
    category: {
      my: 'ကုန်သွယ်ရေး',
      en: 'Commerce',
      zh: '商业',
      de: 'Handel',
    },
    tags: {
      my: ['မီနူ', 'စားသောက်ဆိုင်', 'အစားအစာ', 'သောက်စရာ', 'ကုန်သွယ်ရေး', 'စျေးနှုန်းများ', '၁၉၇၀'],
      en: ['menu', 'restaurant', 'food', 'beverages', 'commerce', 'prices', '1970s'],
      zh: ['菜单', '餐厅', '食物', '饮料', '商业', '价格', '1970年代'],
      de: ['Menü', 'Restaurant', 'Essen', 'Getränke', 'Handel', 'Preise', '1970er'],
    },
    imageUrl: '/images/restaurant-menu-cold-drinks.jpg',
    thumbnailUrl: '/images/restaurant-menu-cold-drinks.jpg',
    historicalContext: {
      my: 'ဤမီနူသည် ၁၉၇၀ ပြည့်လွန်နှစ်များက မြန်မာနိုင်ငံ၏ ဆိုရှယ်လစ် ခေတ်အတွင်း စားသောက်ဆိုင်များ၏ ချက်ပြုတ်ရေး ကမ်းလှမ်းမှုများနှင့် စျေးနှုန်းများကို ထိုးထွင်းသိမြင်စေသည်။ စာရင်းပါ အရာများသည် ရှေးရိုးရာ ဒေသတွင်း သောက်စရာများ (ဥပမာ - ဘာလီရေ၊ ဇီးသံပုရာရည်) နှင့် နိုင်ငံတကာ အမှတ်တံဆိပ်များ (Horlicks, Milo, Nescafe, Ovaltine) တို့ကို ရောနှောထားပြီး၊ ဒေသတွင်း အရသာများနှင့် တင်သွင်းထားသော ထုတ်ကုန်များကို ထင်ဟပ်စေသည်။ ကျပ်နှင့် ပြားဖြင့် စျေးနှုန်းများသည် ထိုခေတ်က ငွေကြေး စနစ်ကို ပြသနေသည်။ မှတ်တမ်း၏ ခေတ်ဟောင်း ပုံစံနှင့် လက်ရေးပုံစံ layout သည် ခေတ်ကာလ စားသောက်ဆိုင် မီနူများ၏ လက္ခဏာရပ်ဖြစ်သည်။',
      en: 'This menu provides insight into the culinary offerings and pricing of restaurants during the 1970s socialist era in Myanmar. The items listed show a mix of traditional local beverages (like barley water, jujube lemonade) and international brands (Horlicks, Milo, Nescafe, Ovaltine), reflecting both local tastes and imported products. The pricing in Kyat and Pya shows the currency system of the time. The document\'s aged appearance and handwritten-style layout are characteristic of period restaurant menus.',
      zh: '这份菜单提供了1970年代社会主义时期缅甸餐厅的烹饪产品和定价的见解。列出的项目显示了传统本地饮料（如大麦水、枣柠檬水）和国际品牌（Horlicks、Milo、Nescafe、Ovaltine）的混合，反映了本地口味和进口产品。以缅元和分计价显示了当时的货币系统。文件的陈旧外观和手写式布局是那个时期餐厅菜单的特征。',
      de: 'Dieses Menü gibt Einblicke in die kulinarischen Angebote und Preise von Restaurants während der sozialistischen Ära der 1970er Jahre in Myanmar. Die aufgelisteten Artikel zeigen eine Mischung aus traditionellen lokalen Getränken (wie Gerstenwasser, Jujube-Limonade) und internationalen Marken (Horlicks, Milo, Nescafe, Ovaltine), die sowohl lokale Geschmäcker als auch importierte Produkte widerspiegeln. Die Preisgestaltung in Kyat und Pya zeigt das Währungssystem der Zeit. Das gealterte Erscheinungsbild des Dokuments und das handgeschriebene Layout sind charakteristisch für Restaurant-Menüs dieser Zeit.',
    },
    source: {
      my: 'ချက်ပြုတ်ရေး စုစည်းရာ',
      en: 'Culinary Archive Collection',
      zh: '烹饪档案收藏',
      de: 'Kulinarisches Archiv',
    },
  },
  {
    id: '5',
    title: {
      my: 'သတ္တဘိန္နူဘုရား - ခေတ်ဟောင်း အနက်ရောင်-အဖြူရောင် (၁၈၅၅)',
      en: 'Thatbyinnyu Temple - Vintage Black & White (1855)',
      zh: '他冰瑜寺 - 复古黑白 (1855)',
      de: 'Thatbyinnyu-Tempel - Vintage Schwarz-Weiß (1855)',
    },
    description: {
      my: 'ပုဂံ၊ မြန်မာနိုင်ငံရှိ သတ္တဘိန္နူဘုရား၏ ခေတ်ဟောင်း အနက်ရောင်-အဖြူရောင် ဓာတ်ပုံ၊ မိုးကောင်းကင်အောက်တွင် ကြီးမားသော အဆင့်များစွာ ဗုဒ္ဓဘာသာ ပုထိုးကို ပြသနေသည်။ မှုန်ဝါးသော၊ ခေတ်ဟောင်း ဓာတ်ပုံသည် ဘုရားကို ၎င်း၏ ရှေးဟောင်း ခန့်ညားမှုအတွင်း ဖမ်းယူထားပြီး၊ ရှားပါးသော ပေါင်းပင်များနှင့် အကွာအဝေးတွင် အခြား ဘုရားပုထိုး အဆောက်အဦများ ဝန်းရံထားသည်။',
      en: 'A vintage black and white photograph of the Thatbyinnyu Temple in Bagan, Myanmar, showing the grand multi-tiered Buddhist pagoda under an overcast sky. The grainy, aged photograph captures the temple in its ancient splendor, surrounded by sparse vegetation and other temple structures in the distance.',
      zh: '缅甸蒲甘他冰瑜寺的复古黑白照片，显示在阴云密布的天空下宏伟的多层佛教佛塔。颗粒感、老化的照片捕捉了寺庙的古老辉煌，周围是稀疏的植被和远处的其他寺庙建筑。',
      de: 'Ein altmodisches Schwarz-Weiß-Foto des Thatbyinnyu-Tempels in Bagan, Myanmar, das die große mehrstöckige buddhistische Pagode unter einem bewölkten Himmel zeigt. Das körnige, gealterte Foto erfasst den Tempel in seiner antiken Pracht, umgeben von spärlicher Vegetation und anderen Tempelstrukturen in der Ferne.',
    },
    year: 1960,
    decade: '1960s',
    era: 'Post-Independence',
    location: {
      my: 'ပုဂံ',
      en: 'Bagan',
      zh: '蒲甘',
      de: 'Bagan',
    },
    category: {
      my: 'ဗိသုကာ',
      en: 'Architecture',
      zh: '建筑',
      de: 'Architektur',
    },
    tags: {
      my: ['ဘုရား', 'ပုထိုး', 'ပုဂံ', 'ဗုဒ္ဓဘာသာ', 'ဗိသုကာ', 'ခေတ်ဟောင်း', 'အနက်ရောင်-အဖြူရောင်', '၁၈၅၅'],
      en: ['temple', 'pagoda', 'bagan', 'buddhist', 'architecture', 'vintage', 'black-white', '1855'],
      zh: ['寺庙', '佛塔', '蒲甘', '佛教', '建筑', '复古', '黑白', '1855'],
      de: ['Tempel', 'Pagode', 'Bagan', 'buddhistisch', 'Architektur', 'Vintage', 'Schwarz-Weiß', '1855'],
    },
    imageUrl: '/images/thatbyinnyu-temple-vintage-bw.jpg',
    thumbnailUrl: '/images/thatbyinnyu-temple-vintage-bw.jpg',
    historicalContext: {
      my: 'သတ္တဘိန္နူဘုရား၊ ၁၈၅၅ ခုနှစ်တွင် တည်ဆောက်ခဲ့သည်၊ ပုဂံရှေးဟောင်း သုတေသန ဇုန်ရှိ အရ်အမြင့်ဆုံး နှင့် အထင်ရှားဆုံး ဘုရားများထဲမှ တစ်ခုဖြစ်သည်။ ဤခေတ်ဟောင်း အနက်ရောင်-အဖြူရောင် ဓာတ်ပုံသည် ၂၀ ရာစု အလယ်ပိုင်းက ဘုရားကို ဖမ်းယူထားပြီး၊ ၎င်း၏ ရာသီဥတု ထိခိုက်ထားသော ကျောက်တုံး ဖွဲ့စည်းပုံနှင့် အနုစိတ် ဗိသုကာ အသေးစိတ်များကို ပြသနေသည်။ မိုးကောင်းကင်နှင့် မှုန်ဝါးသော အရည်အသွေးသည် ၎င်း၏ သမိုင်းဝင် စရိုက်လက္ခဏာကို ထပ်တိုးစေပြီး၊ ဘုရားပုထိုးစဉ်သည် လျော့နည်းစွာ ဖွံ့ဖြိုးတိုးတက်ပြီး ပိုမို ခွဲထားသော အချိန်ကို ထိန်းသိမ်းထားသည်။',
      en: 'The Thatbyinnyu Temple, built in 1855, is one of the tallest and most prominent temples in the Bagan Archaeological Zone. This vintage black and white photograph captures the temple during the mid-20th century, showing its weathered stone structure and intricate architectural details. The overcast sky and grainy quality of the photograph add to its historical character, preserving a moment when the temple complex was less developed and more isolated.',
      zh: '他冰瑜寺建于1855年，是蒲甘考古区最高和最突出的寺庙之一。这张复古黑白照片捕捉了20世纪中期的寺庙，显示了其风化的石结构和复杂的建筑细节。阴云密布的天空和照片的颗粒感增加了其历史特征，保存了寺庙群不那么发达和更加孤立的时刻。',
      de: 'Der Thatbyinnyu-Tempel, erbaut 1855, ist einer der höchsten und prominentesten Tempel in der archäologischen Zone von Bagan. Dieses altmodische Schwarz-Weiß-Foto erfasst den Tempel aus der Mitte des 20. Jahrhunderts und zeigt seine verwitterte Steinstruktur und aufwendige architektonische Details. Der bewölkte Himmel und die körnige Qualität des Fotos tragen zu seinem historischen Charakter bei und bewahren einen Moment, als der Tempelkomplex weniger entwickelt und isolierter war.',
    },
    source: {
      my: 'သမိုင်းဝင် ဓာတ်ပုံ စုစည်းရာ',
      en: 'Historical Photographic Archive',
      zh: '历史摄影档案',
      de: 'Historisches Fotografisches Archiv',
    },
    beforeImageId: '5',
    afterImageId: '6',
  },
  {
    id: '6',
    title: {
      my: 'သတ္တဘိန္နူဘုရား - ခေတ်မီ မြင်ကွင်း',
      en: 'Thatbyinnyu Temple - Modern View',
      zh: '他冰瑜寺 - 现代景观',
      de: 'Thatbyinnyu-Tempel - Moderne Ansicht',
    },
    description: {
      my: 'ပုဂံ၊ မြန်မာနိုင်ငံရှိ သတ္တဘိန္နူဘုရား၏ ခေတ်မီ အရောင်ဓာတ်ပုံ၊ တူညီသော ကြီးမားသော ဘုရား ဖွဲ့စည်းပုံကို ရှင်းလင်းသော အပြာရောင် မိုးကောင်းကင်အောက်တွင် ပြသနေသည်။ ပုံသည် ရွှေရောင် spires များ၊ စျေးဆိုင်များ၊ သစ်ပင်များနှင့် ခေတ်မီ အရာများဖြင့် ဝန်းရံထားသော ဘုရားကို ဖမ်းယူထားပြီး၊ ရှေးဟောင်း နေရာသည် ခေတ်မီ နေ့စဉ် ဘဝထဲသို့ မည်သို့ ပေါင်းစပ်ထားကြောင်း ပြသနေသည်။',
      en: 'A modern color photograph of the Thatbyinnyu Temple in Bagan, Myanmar, showing the same grand temple structure under a clear blue sky. The image captures the temple with its golden spires, surrounded by market stalls, trees, and modern elements, showing how the ancient site has become integrated into contemporary daily life.',
      zh: '缅甸蒲甘他冰瑜寺的现代彩色照片，显示在晴朗的蓝天下相同的宏伟寺庙结构。图像捕捉了带有金色尖顶的寺庙，周围是市场摊位、树木和现代元素，展示了古代遗址如何融入当代日常生活。',
      de: 'Ein modernes Farbfoto des Thatbyinnyu-Tempels in Bagan, Myanmar, das dieselbe große Tempelstruktur unter einem klaren blauen Himmel zeigt. Das Bild erfasst den Tempel mit seinen goldenen Türmen, umgeben von Marktständen, Bäumen und modernen Elementen und zeigt, wie die antike Stätte in das zeitgenössische tägliche Leben integriert wurde.',
    },
    year: 2020,
    decade: '2010s',
    era: 'Modern Era',
    location: {
      my: 'ပုဂံ',
      en: 'Bagan',
      zh: '蒲甘',
      de: 'Bagan',
    },
    category: {
      my: 'ဗိသုကာ',
      en: 'Architecture',
      zh: '建筑',
      de: 'Architektur',
    },
    tags: {
      my: ['ဘုရား', 'ပုထိုး', 'ပုဂံ', 'ဗုဒ္ဓဘာသာ', 'ဗိသုကာ', 'ခေတ်မီ', 'အရောင်', 'ခရီးသွားလုပ်ငန်း'],
      en: ['temple', 'pagoda', 'bagan', 'buddhist', 'architecture', 'modern', 'color', 'tourism'],
      zh: ['寺庙', '佛塔', '蒲甘', '佛教', '建筑', '现代', '彩色', '旅游'],
      de: ['Tempel', 'Pagode', 'Bagan', 'buddhistisch', 'Architektur', 'modern', 'Farbe', 'Tourismus'],
    },
    imageUrl: '/images/thatbyinnyu-temple-modern.jpg',
    thumbnailUrl: '/images/thatbyinnyu-temple-modern.jpg',
    historicalContext: {
      my: 'သတ္တဘိန္နူဘုရား၏ ဤခေတ်မီ မြင်ကွင်းသည် ရှေးဟောင်း နေရာ၏ ပြောင်းလဲလာပုံကို ပြသနေသည်။ ၁၈၅၅ ခုနှစ်တွင် တည်ဆောက်ခဲ့သော ဘုရားသည် ယခု ပုဂံရှိ အဓိက ခရီးသွား ဆွဲဆောင်ရာ နေရာတစ်ခု အဖြစ် ရပ်တည်နေသည်။ စျေးဆိုင်များ၊ ဆိုင်းဘုတ်များနှင့် ခေတ်မီ အခြေခံအဆောက်အဦများ၏ ရှိနေမှုသည် ခရီးသွားလုပ်ငန်း၏ ကြီးထွားမှုနှင့် မြန်မာနိုင်ငံရှိ သမိုင်းဝင် နေရာများ၏ ခေတ်မီ ဘဝထဲသို့ ပေါင်းစပ်မှုကို ထင်ဟပ်စေသည်။ ရှင်းလင်းသော အပြာရောင် မိုးကောင်းကင်နှင့် လှပသော အရောင်များသည် ခေတ်ဟောင်း ဓာတ်ပုံများနှင့် ကွဲပြားပြီး၊ ဤသန့်ရှင်းသော နေရာကို အတွေ့အကြုံရရှိပုံကို ဆက်လက် ရှိနေမှုနှင့် ပြောင်းလဲမှုကို ပြသနေသည်။',
      en: 'This modern view of the Thatbyinnyu Temple shows how the ancient site has evolved. The temple, built in 1855, now stands as a major tourist attraction in Bagan. The presence of market stalls, signage, and modern infrastructure around the temple reflects the growth of tourism and the integration of historical sites into contemporary Myanmar. The clear blue sky and vibrant colors contrast with vintage photographs, showing both continuity and change in how this sacred site is experienced.',
      zh: '他冰瑜寺的现代景观展示了古代遗址的演变。建于1855年的寺庙现在是蒲甘的主要旅游景点。寺庙周围的市场摊位、标牌和现代基础设施的存在反映了旅游业的发展以及历史遗址融入当代缅甸的情况。晴朗的蓝天和鲜艳的色彩与复古照片形成对比，展示了这个神圣遗址体验方式的连续性和变化。',
      de: 'Diese moderne Ansicht des Thatbyinnyu-Tempels zeigt, wie sich die antike Stätte entwickelt hat. Der 1855 erbaute Tempel steht heute als Haupttouristenattraktion in Bagan. Die Anwesenheit von Marktständen, Beschilderung und moderner Infrastruktur um den Tempel spiegelt das Wachstum des Tourismus und die Integration historischer Stätten in das zeitgenössische Myanmar wider. Der klare blaue Himmel und die lebendigen Farben kontrastieren mit Vintage-Fotos und zeigen sowohl Kontinuität als auch Wandel in der Art und Weise, wie diese heilige Stätte erlebt wird.',
    },
    source: {
      my: 'ခေတ်မီ ဓာတ်ပုံ စုစည်းရာ',
      en: 'Modern Photographic Archive',
      zh: '现代摄影档案',
      de: 'Modernes Fotografisches Archiv',
    },
    beforeImageId: '5',
    afterImageId: '6',
  },
];

export const eras = [
  'Pre-Colonial',
  'Colonial Era',
  'Post-Independence',
  'Socialist Era',
  'Modern Era',
];

export const categories = [
  'Urban Life',
  'Rural Life',
  'Fashion',
  'Commerce',
  'Transportation',
  'Architecture',
  'Entertainment',
  'Education',
  'Religion',
  'Other',
];

export const decades = [
  '1940s',
  '1950s',
  '1960s',
  '1970s',
  '1980s',
  '1990s',
  '2000s',
  '2010s',
];
